"""
GET /api/crm/unsubscribe/{token} — public unsubscribe landing page.

Token is a short-lived JWT generated by email_renderer when expanding {{unsubscribe_url}}.
On success: insert into crm_unsubscribes with source='email_link', return a simple HTML page.

BE Dev 2 fills in Sprint 4. This is a stub.
"""

import logging
from typing import Any, Dict

logger = logging.getLogger(__name__)


def handle_unsubscribe(token: str, db_session) -> Dict[str, Any]:
    """
    Returns an API Gateway proxy response with text/html body.
    """
    # BE Dev 2: decode JWT token, extract {user_location_id, email, exp};
    # insert row into crm_unsubscribes; render confirmation HTML.
    return {
        "statusCode": 200,
        "headers": {"Content-Type": "text/html; charset=utf-8"},
        "body": (
            "<!doctype html><html><body style=\"font-family:sans-serif;padding:40px;text-align:center\">"
            "<h1>Unsubscribe</h1>"
            "<p>Implementation pending (BE Dev 2, Sprint 4).</p>"
            "</body></html>"
        ),
    }
