"""
GET /api/crm/unsubscribe/{token} — public unsubscribe landing page.

Token is an HMAC-SHA256-signed token generated by unsubscribe_token.make_unsub_url().
On success:
  - INSERT into crm_unsubscribes with source='email_link' (ON CONFLICT DO NOTHING)
  - Return a small HTML confirmation page

On invalid token:
  - Return 400 HTML page "Invalid or expired link."
"""

import logging
from typing import Any, Dict

from sqlalchemy import text

logger = logging.getLogger(__name__)

_PAGE_OK = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Unsubscribed — GEPP</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {{ font-family: sans-serif; text-align: center; padding: 60px 20px; color: #333; }}
    h1 {{ font-size: 1.8rem; margin-bottom: .5rem; }}
    p  {{ color: #666; }}
  </style>
</head>
<body>
  <h1>You've been unsubscribed.</h1>
  <p>You will no longer receive marketing emails from GEPP.</p>
  <p style="margin-top:2rem;font-size:.85rem;">— GEPP</p>
</body>
</html>"""

_PAGE_BAD = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Invalid Link — GEPP</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {{ font-family: sans-serif; text-align: center; padding: 60px 20px; color: #333; }}
    h1 {{ font-size: 1.8rem; margin-bottom: .5rem; color: #c00; }}
    p  {{ color: #666; }}
  </style>
</head>
<body>
  <h1>Invalid or expired link.</h1>
  <p>This unsubscribe link is not valid. Please contact support if you need help.</p>
</body>
</html>"""


def handle_unsubscribe(token: str, db_session) -> Dict[str, Any]:
    """
    Returns an API Gateway proxy response with text/html body.

    Args:
        token:      URL path segment — the HMAC-signed token from make_unsub_url().
        db_session: SQLAlchemy session (may be None in tests without DB).

    Returns:
        API Gateway proxy response dict with statusCode + headers + body.
    """
    from GEPPPlatform.services.admin.crm.unsubscribe_token import verify_unsub_token

    email = verify_unsub_token(token)
    if not email:
        logger.info("crm_unsubscribe_handler: invalid token (prefix=%s...)", token[:8])
        return {
            "statusCode": 400,
            "headers": {"Content-Type": "text/html; charset=utf-8"},
            "body": _PAGE_BAD,
        }

    # INSERT — idempotent, ON CONFLICT DO NOTHING
    if db_session is not None:
        try:
            db_session.execute(
                text("""
                    INSERT INTO crm_unsubscribes (email, source, unsubscribed_at)
                    VALUES (:email, 'email_link', NOW())
                    ON CONFLICT (email) DO NOTHING
                """),
                {"email": email},
            )
            db_session.commit()
            logger.info("crm_unsubscribe_handler: unsubscribed email=%s", email)
        except Exception as exc:
            logger.error("crm_unsubscribe_handler: DB error for email=%s: %s", email, exc)
            try:
                db_session.rollback()
            except Exception:
                pass
            # Still show the success page — the user's intent is clear
    else:
        logger.warning("crm_unsubscribe_handler: no db_session provided — skipping DB insert")

    return {
        "statusCode": 200,
        "headers": {"Content-Type": "text/html; charset=utf-8"},
        "body": _PAGE_OK,
    }
